"""empty message

Revision ID: 7460ec709597
Revises: 7301acd51637
Create Date: 2021-06-05 15:50:33.455176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7460ec709597'
down_revision = '7301acd51637'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fooditem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resturant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('shippinginfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('foodMenu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['title'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orderedAt', sa.DateTime(), nullable=False),
    sa.Column('deliveredAt', sa.String(), nullable=True),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('paymentMethod', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('shippingInfo_id', sa.Integer(), nullable=False),
    sa.Column('shippingCost', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['shippingInfo_id'], ['shippinginfo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orderitems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('foodItemName', sa.String(), nullable=False),
    sa.Column('unitPrice', sa.Float(), nullable=False),
    sa.Column('subTotal', sa.Float(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('fooditem_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fooditem_id'], ['fooditem.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('user_name_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_name_key', 'user', ['name'])
    op.drop_table('orderitems')
    op.drop_table('orders')
    op.drop_table('foodMenu')
    op.drop_table('shippinginfo')
    op.drop_table('resturant')
    op.drop_table('fooditem')
    # ### end Alembic commands ###
